### ISSUE TITLE
Find and replace widget not rendering icons

### ISSUE THREAD

**Issue by wxirxn-bifrost** [echarles/jupyter-nextjs-example#2]
When finding and replacing text on a notebook, the icons for the various buttons within the widget (Match Case, Match Whole Word, Next/Previous Match etc.) don't render. The buttons themselves still work - clicking them works and their hoverstates still change the styles - but the icons don't exist in the HTML.

<img width="424" alt="image" src="https://github.com/echarles/jupyter-nextjs-example/assets/118256315/9a369681-c6b9-43f2-8b6d-20da291a2ded">

<img width="1046" alt="image" src="https://github.com/echarles/jupyter-nextjs-example/assets/118256315/be7ea0e9-230b-43f6-a1d1-889598298978">

This is running directly off the example code with no changes.

**Comment by echarles** [comment]
Thx for reporting. I can reproduce on this codesandbox https://codesandbox.io/p/devbox/jupyter-react-nextjs-qzv8cz - https://qzv8cz-3000.csb.app

There is a need for custom webpack to display those icons https://nextjs.org/docs/app/api-reference/next-config-js/webpack

**Comment by echarles** [comment]
https://github.com/datalayer-examples/jupyter-nextjs-example/commit/3025618c9e3e6167462e18f2328fe361ce61e278 fixes this.

![Screenshot from 2024-05-13 10-36-47](https://github.com/datalayer-examples/jupyter-nextjs-example/assets/226720/de126bb1-8582-4835-8b54-f28b45cc6c74)

**Comment by wxirxn-bifrost** [comment]
Does `svg-url-loader` have to be installed in the project for this to work?

**Comment by echarles** [comment]
Yep, just pushed https://github.com/datalayer-examples/jupyter-nextjs-example/commit/3cc7380c64b10a19fec1ab4ed6ff5fd4b873ba58 for that :+1:

**Comment by wxirxn-bifrost** [comment]
Just tested it on my machine - the issue has been resolved. Thanks!
